import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

type Analytics = { uniqueWebsiteVisitors: number; uniqueQrScanners: number; uniqueQrScans: number; profileSubmissions: number; today: { uniqueWebsiteVisitors: number; uniqueQrScanners: number; profileSubmissions: number }; last7Days: { uniqueWebsiteVisitors: number; uniqueQrScanners: number; profileSubmissions: number }; scansByTable: { tableId: string | null; uniqueScans: number }[]; customerProfiles: { name: string; phone: string; tableId: string | null; submittedAt: string }[] };
const request = (url: string, options?: RequestInit) => fetch(url, { credentials: "include", ...options });
const maskPhone = (phone: string) => phone.length < 5 ? "••••" : `${phone.slice(0, 5)}${"•".repeat(Math.max(4, phone.length - 5))}`;

export default function DeveloperAnalytics() {
  const [code, setCode] = useState(""); const [loginError, setLoginError] = useState(""); const [authenticated, setAuthenticated] = useState(false);
  const analytics = useQuery<Analytics>({ queryKey: ["developer-analytics"], enabled: authenticated, queryFn: async () => { const response = await request("/api/developer/analytics"); if (!response.ok) throw new Error("Your developer session has expired."); return response.json(); } });
  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoginError(""); const response = await request("/api/developer/auth/totp", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code }) }); if (!response.ok) { setLoginError(response.status === 429 ? "Too many attempts. Please wait and try again." : "Invalid authenticator code."); return; } setAuthenticated(true); setCode(""); };
  const logout = async () => { await request("/api/developer/auth/logout", { method: "POST" }); setAuthenticated(false); };
  if (!authenticated) return <main className="min-h-screen bg-background grid place-items-center p-4"><form onSubmit={login} className="w-full max-w-sm rounded-2xl border border-border bg-card p-6 shadow-sm"><h1 className="text-xl font-bold">Developer analytics</h1><p className="mt-1 text-sm text-muted-foreground">Enter your authenticator code to continue.</p><input aria-label="Authenticator code" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" className="mt-5 w-full rounded-lg border border-border bg-background px-3 py-2 text-center tracking-[0.4em]" /><button className="mt-4 w-full rounded-lg bg-primary px-4 py-2.5 font-semibold text-primary-foreground">Verify</button>{loginError && <p className="mt-3 text-sm text-destructive">{loginError}</p>}</form></main>;
  if (analytics.isLoading) return <main className="min-h-screen bg-background p-8">Loading analytics…</main>;
  if (analytics.isError || !analytics.data) return <main className="min-h-screen bg-background p-8"><p>Unable to load analytics. Your session may have expired.</p><button onClick={logout} className="mt-4 underline">Sign in again</button></main>;
  const data = analytics.data;
  return <main className="min-h-screen bg-background p-4 md:p-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Developer analytics</h1><p className="text-sm text-muted-foreground">Customer numbers are masked by default.</p></div><button onClick={logout} className="rounded border border-border px-3 py-2 text-sm">Sign out</button></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Website visitors", data.uniqueWebsiteVisitors], ["Unique QR scanners", data.uniqueQrScanners], ["QR scans", data.uniqueQrScans], ["Profile submissions", data.profileSubmissions]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>)}</section><section className="mt-6 grid gap-4 md:grid-cols-2"><MetricPeriod title="Today" data={data.today} /><MetricPeriod title="Last 7 days" data={data.last7Days} /></section><section className="mt-8 rounded-xl border border-border bg-card p-5"><h2 className="font-bold">QR scans by table</h2><table className="mt-4 w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="pb-2">Table</th><th className="pb-2">Unique scans</th></tr></thead><tbody>{data.scansByTable.map((row) => <tr key={row.tableId ?? "unknown"} className="border-t border-border"><td className="py-2">{row.tableId ?? "Unknown"}</td><td className="py-2">{row.uniqueScans}</td></tr>)}</tbody></table></section><section className="mt-8 rounded-xl border border-border bg-card p-5"><h2 className="font-bold">Customer profiles</h2><div className="overflow-x-auto"><table className="mt-4 w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="pb-2">Name</th><th className="pb-2">Phone</th><th className="pb-2">Table</th><th className="pb-2">Submitted</th></tr></thead><tbody>{data.customerProfiles.map((row, index) => <tr key={`${row.submittedAt}-${index}`} className="border-t border-border"><td className="py-2">{row.name}</td><td className="py-2">{maskPhone(row.phone)}</td><td className="py-2">{row.tableId ?? "—"}</td><td className="py-2">{new Date(row.submittedAt).toLocaleString()}</td></tr>)}</tbody></table></div></section></div></main>;
}
function MetricPeriod({ title, data }: { title: string; data: Analytics["today"] }) { return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-bold">{title}</h2><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-muted-foreground">Visitors</dt><dd className="font-bold">{data.uniqueWebsiteVisitors}</dd></div><div><dt className="text-muted-foreground">QR scanners</dt><dd className="font-bold">{data.uniqueQrScanners}</dd></div><div><dt className="text-muted-foreground">Profiles</dt><dd className="font-bold">{data.profileSubmissions}</dd></div></dl></section>; }
