import { useQuery } from "@tanstack/react-query";

type Analytics = { uniqueWebsiteVisitors: number; uniqueQrScanners: number; uniqueQrScans: number; profileSubmissions: number; today: { uniqueWebsiteVisitors: number; uniqueQrScanners: number; profileSubmissions: number }; last7Days: { uniqueWebsiteVisitors: number; uniqueQrScanners: number; profileSubmissions: number }; scansByTable: { tableId: string | null; uniqueScans: number }[]; customerProfiles: { name: string; phone: string; tableId: string | null; submittedAt: string }[] };
const request = (url: string, options?: RequestInit) => fetch(url, { credentials: "include", ...options });

export default function DeveloperAnalytics() {
  const analytics = useQuery<Analytics>({ queryKey: ["developer-analytics"], queryFn: async () => { const response = await request("/api/developer/internal-metrics-dashboard-v2-a8f3e9d1c4b7"); if (!response.ok) throw new Error("Unable to load analytics data."); return response.json(); } });
  if (analytics.isLoading) return <main className="min-h-screen bg-background p-8">Loading analytics…</main>;
  if (analytics.isError || !analytics.data) return <main className="min-h-screen bg-background p-8"><p>Unable to load analytics data. Please try again later.</p></main>;
  const data = analytics.data;
  return <main className="min-h-screen bg-background p-4 md:p-8"><div className="mx-auto max-w-6xl"><header className="mb-8"><h1 className="text-2xl font-bold">Developer Analytics</h1><p className="text-sm text-muted-foreground">Real-time analytics dashboard for Sher-E-Punjab. Full customer data for WhatsApp group management.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Website visitors", data.uniqueWebsiteVisitors], ["Unique QR scanners", data.uniqueQrScanners], ["QR scans", data.uniqueQrScans], ["Profile submissions", data.profileSubmissions]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>)}</section><section className="mt-6 grid gap-4 md:grid-cols-2"><MetricPeriod title="Today" data={data.today} /><MetricPeriod title="Last 7 days" data={data.last7Days} /></section><section className="mt-8 rounded-xl border border-border bg-card p-5"><h2 className="font-bold">QR scans by table</h2><table className="mt-4 w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="pb-2">Table</th><th className="pb-2">Unique scans</th></tr></thead><tbody>{data.scansByTable.map((row) => <tr key={row.tableId ?? "unknown"} className="border-t border-border"><td className="py-2">{row.tableId ?? "Unknown"}</td><td className="py-2">{row.uniqueScans}</td></tr>)}</tbody></table></section><section className="mt-8 rounded-xl border border-border bg-card p-5"><h2 className="font-bold">Customer profiles</h2><p className="mt-1 text-xs text-muted-foreground">Full contact details for WhatsApp group creation</p><div className="overflow-x-auto"><table className="mt-4 w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="pb-2">Name</th><th className="pb-2">Phone</th><th className="pb-2">Table</th><th className="pb-2">Submitted</th></tr></thead><tbody>{data.customerProfiles.map((row, index) => <tr key={`${row.submittedAt}-${index}`} className="border-t border-border"><td className="py-2">{row.name}</td><td className="py-2 font-mono">{row.phone}</td><td className="py-2">{row.tableId ?? "—"}</td><td className="py-2">{new Date(row.submittedAt).toLocaleString()}</td></tr>)}</tbody></table></div></section></div></main>;
}
function MetricPeriod({ title, data }: { title: string; data: Analytics["today"] }) { return <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-bold">{title}</h2><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-muted-foreground">Visitors</dt><dd className="font-bold">{data.uniqueWebsiteVisitors}</dd></div><div><dt className="text-muted-foreground">QR scanners</dt><dd className="font-bold">{data.uniqueQrScanners}</dd></div><div><dt className="text-muted-foreground">Profiles</dt><dd className="font-bold">{data.profileSubmissions}</dd></div></dl></section>; }
